language: node_js
node_js:
  - "node"

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always

branches:
  except: # blocklist - wont run travis on these
  - master
  only: # safelist - will run travis on these
  - gen_tracks

before_script:
  - npm install dotenv --save
  - npm install tape --save
  - npm install --save @mapbox/togeojson

#deploy:
#  provider: pages
#  skip_cleanup: true
#  github_token: $PUB_REP_TOKEN
#  on:
#    branch: gen_tracks
#  local_dir: tracks/gpx
#  target_branch: gen_tracks

#deploy:
#  provider: releases
#  api_key: "GITHUB OAUTH TOKEN"
#  file: "FILE TO UPLOAD"
#  skip_cleanup: true
#  on:
#    tags: true
