language: node_js
node_js:
  - "node"

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always

before_script:
  - npm install dotenv --save
  - npm install tape --save
  - npm install --save @mapbox/togeojson

#deploy:
#  provider: pages
#  skip_cleanup: true
#  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
#  on:
#    branch: master
